[project]
name = "mcp-servers"
version = "0.1.0"
description = "Expense Tracker MCP Server"
readme = "README.md"
authors = [
    { name = "Abhay Keshari", email = "instantboostbyabhaykeshari@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "fastmcp>=4.0.3",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
]

[project.scripts]
mcp-servers = "server:main"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["server", "database"]

[tool.setuptools.package-dir]
"" = "."