CREATE TABLE IF NOT EXISTS expenses (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    amount NUMERIC(10, 2) NOT NULL,
    category VARCHAR(100) NOT NULL,
	sub_category VARCHAR(100),
    description TEXT,
    expense_date DATE DEFAULT CURRENT_DATE
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);